### ISSUE TITLE
http IncomingMessage is not a Readable

### ISSUE THREAD

**Issue by mcollina** [calvinmetcalf/async-iter-stream#2]
We would need to provide an implementation also for streams 1.

**Comment by calvinmetcalf** [comment]
is there any prior art on effectively/efficiently doing `read(function (err, data){})` on streams across versions?

**Comment by mcollina** [comment]
https://nodejs.org/api/stream.html#stream_readable_wrap_stream

**Comment by calvinmetcalf** [comment]
would the absence of readable.wrap be a good test to see if it's a streams1 ?

**Comment by mcollina** [comment]
I think we can just check if it has a `_readableState`.

**Comment by calvinmetcalf** [comment]
done in the wrap method
